# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ad.proto',
  package='ad',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x08\x61\x64.proto\x12\x02\x61\x64\"G\n\x02\x41\x64\x12\x16\n\x04user\x18\x01 \x01(\x0b\x32\x08.ad.User\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"\x1a\n\x07\x41\x64Reply\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"\x1a\n\x03\x41\x64s\x12\x13\n\x03\x61\x64s\x18\x01 \x03(\x0b\x32\x06.ad.Ad2\x8e\x01\n\tAdService\x12\x1f\n\x06SendAd\x12\x06.ad.Ad\x1a\x0b.ad.AdReply\"\x00\x12\x1d\n\x06GetAds\x12\x08.ad.User\x1a\x07.ad.Ads\"\x00\x12 \n\tGetUserAd\x12\x08.ad.User\x1a\x07.ad.Ads\"\x00\x12\x1f\n\x04Sign\x12\x08.ad.User\x1a\x0b.ad.AdReply\"\x00\x62\x06proto3')
)




_AD = _descriptor.Descriptor(
  name='Ad',
  full_name='ad.Ad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='ad.Ad.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='ad.Ad.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='ad.Ad.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='ad.Ad.date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=87,
)


_ADREPLY = _descriptor.Descriptor(
  name='AdReply',
  full_name='ad.AdReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ad.AdReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=115,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='ad.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ad.User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='ad.User.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=152,
)


_ADS = _descriptor.Descriptor(
  name='Ads',
  full_name='ad.Ads',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ads', full_name='ad.Ads.ads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=180,
)

_AD.fields_by_name['user'].message_type = _USER
_ADS.fields_by_name['ads'].message_type = _AD
DESCRIPTOR.message_types_by_name['Ad'] = _AD
DESCRIPTOR.message_types_by_name['AdReply'] = _ADREPLY
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Ads'] = _ADS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ad = _reflection.GeneratedProtocolMessageType('Ad', (_message.Message,), dict(
  DESCRIPTOR = _AD,
  __module__ = 'ad_pb2'
  # @@protoc_insertion_point(class_scope:ad.Ad)
  ))
_sym_db.RegisterMessage(Ad)

AdReply = _reflection.GeneratedProtocolMessageType('AdReply', (_message.Message,), dict(
  DESCRIPTOR = _ADREPLY,
  __module__ = 'ad_pb2'
  # @@protoc_insertion_point(class_scope:ad.AdReply)
  ))
_sym_db.RegisterMessage(AdReply)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'ad_pb2'
  # @@protoc_insertion_point(class_scope:ad.User)
  ))
_sym_db.RegisterMessage(User)

Ads = _reflection.GeneratedProtocolMessageType('Ads', (_message.Message,), dict(
  DESCRIPTOR = _ADS,
  __module__ = 'ad_pb2'
  # @@protoc_insertion_point(class_scope:ad.Ads)
  ))
_sym_db.RegisterMessage(Ads)



_ADSERVICE = _descriptor.ServiceDescriptor(
  name='AdService',
  full_name='ad.AdService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=183,
  serialized_end=325,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendAd',
    full_name='ad.AdService.SendAd',
    index=0,
    containing_service=None,
    input_type=_AD,
    output_type=_ADREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAds',
    full_name='ad.AdService.GetAds',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_ADS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUserAd',
    full_name='ad.AdService.GetUserAd',
    index=2,
    containing_service=None,
    input_type=_USER,
    output_type=_ADS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Sign',
    full_name='ad.AdService.Sign',
    index=3,
    containing_service=None,
    input_type=_USER,
    output_type=_ADREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADSERVICE)

DESCRIPTOR.services_by_name['AdService'] = _ADSERVICE

# @@protoc_insertion_point(module_scope)
