# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ad_pb2 as ad__pb2


class AdServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendAd = channel.unary_unary(
        '/ad.AdService/SendAd',
        request_serializer=ad__pb2.Ad.SerializeToString,
        response_deserializer=ad__pb2.AdReply.FromString,
        )
    self.GetAds = channel.unary_unary(
        '/ad.AdService/GetAds',
        request_serializer=ad__pb2.User.SerializeToString,
        response_deserializer=ad__pb2.Ads.FromString,
        )
    self.GetUserAd = channel.unary_unary(
        '/ad.AdService/GetUserAd',
        request_serializer=ad__pb2.User.SerializeToString,
        response_deserializer=ad__pb2.Ads.FromString,
        )
    self.Sign = channel.unary_unary(
        '/ad.AdService/Sign',
        request_serializer=ad__pb2.User.SerializeToString,
        response_deserializer=ad__pb2.AdReply.FromString,
        )


class AdServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendAd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAds(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserAd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Sign(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AdServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendAd': grpc.unary_unary_rpc_method_handler(
          servicer.SendAd,
          request_deserializer=ad__pb2.Ad.FromString,
          response_serializer=ad__pb2.AdReply.SerializeToString,
      ),
      'GetAds': grpc.unary_unary_rpc_method_handler(
          servicer.GetAds,
          request_deserializer=ad__pb2.User.FromString,
          response_serializer=ad__pb2.Ads.SerializeToString,
      ),
      'GetUserAd': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserAd,
          request_deserializer=ad__pb2.User.FromString,
          response_serializer=ad__pb2.Ads.SerializeToString,
      ),
      'Sign': grpc.unary_unary_rpc_method_handler(
          servicer.Sign,
          request_deserializer=ad__pb2.User.FromString,
          response_serializer=ad__pb2.AdReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ad.AdService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
