INSERT INTO detail (name, price, color, weight) VALUES ('Гвоздь 50мм',100, 'чёрный',10);
INSERT INTO detail (name, price, color, weight) VALUES ('Гвоздь 100мм',200, 'чёрный',15);
INSERT INTO detail (name, price, color, weight) VALUES ('Гвоздь 150мм',300, 'чёрный',25);
INSERT INTO detail (name, price, color, weight) VALUES ('Гвоздь 200мм',400, 'чёрный',35);
INSERT INTO detail (name, price, color, weight) VALUES ('Саморез 50мм',150, 'синий',10);
INSERT INTO detail (name, price, color, weight) VALUES ('Саморез 100мм',230, 'синий',15);
INSERT INTO detail (name, price, color, weight) VALUES ('Саморез 150мм',290, 'синий',25);
INSERT INTO detail (name, price, color, weight) VALUES ('Саморез 200мм',340, 'синий',33);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 5м',600, 'красный',140);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 10м',900, 'серый',240);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 11м',1000, 'белый',340);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 12м',1100, 'чёрный',390);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 13м',1200, 'красный',440);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 14м',1300, 'синий',490);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 15м',1400, 'серый',540);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 16м',1500, 'зелёный',590);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 17м',1600, 'жёлтый',640);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 18м',1700, 'оранжевый',690);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 19м',1800, 'белый',7400);
INSERT INTO detail (name, price, color, weight) VALUES ('Вагонка 20м',1900, 'синий',790);


INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект1', 'Челябинск', 'пр. Ленина, 3', 1);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект1' , 'Магнитогорск', 'ул. Суворова, 1', 2);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт1', 'Челябинск', 'ул. Энтузиастов, 4', 3);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт1', 'Магнитогорск', 'ул. Доменщиков, 5', 4);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект2', 'Челябинск', 'пр. Ленина, 4', 5);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект2', 'Магнитогорск', 'ул. Суворова, 2', 6);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт2', 'Челябинск', 'ул. Энтузиастов, 5', 7);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт2', 'Магнитогорск', 'ул. Доменщиков, 6', 8);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект3', 'Челябинск', 'пр. Ленина, 5', 9);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект3', 'Магнитогорск', 'ул. Суворова, 3', 10);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт3', 'Челябинск', 'ул. Энтузиастов, 6', 1);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт3', 'Магнитогорск', 'ул. Доменщиков, 7', 2);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект4', 'Челябинск', 'пр. Ленина, 6', 3);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект4', 'Магнитогорск', 'ул. Суворова, 4', 4);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт4', 'Челябинск', 'ул. Энтузиастов, 7', 5);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт4', 'Магнитогорск', 'ул. Доменщиков, 8', 6);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект5', 'Челябинск', 'пр. Ленина, 7', 7);
INSERT INTO provider(name, city, address, rating) VALUES ('Стройкомплект5', 'Магнитогорск', 'ул. Суворова, 5', 8);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт5', 'Челябинск', 'ул. Энтузиастов, 8', 9);
INSERT INTO provider(name, city, address, rating) VALUES ('РемСнабСбыт5', 'Магнитогорск', 'ул. Доменщиков, 9', 10);


INSERT INTO project(name, city, address, budget) VALUES ('Проект 1', 'Челябинск', 'пр. Ленина 1', 10000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 2', 'Челябинск', 'пр. Ленина 2', 20000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 3', 'Челябинск', 'пр. Ленина 3', 30000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 4', 'Челябинск', 'пр. Ленина 4', 40000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 5', 'Челябинск', 'пр. Ленина 5', 50000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 6', 'Челябинск', 'пр. Ленина 6', 60000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 7', 'Челябинск', 'пр. Ленина 7', 70000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 8', 'Челябинск', 'пр. Ленина 8', 80000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 9', 'Челябинск', 'пр. Ленина 9', 90000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 10', 'Челябинск', 'пр. Ленина 10', 100000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 11', 'Челябинск', 'пр. Ленина 11', 110000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 12', 'Челябинск', 'пр. Ленина 12', 120000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 13', 'Челябинск', 'пр. Ленина 13', 130000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 14', 'Челябинск', 'пр. Ленина 14', 140000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 15', 'Челябинск', 'пр. Ленина 15', 150000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 16', 'Челябинск', 'пр. Ленина 16', 160000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 17', 'Челябинск', 'пр. Ленина 17', 170000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 18', 'Челябинск', 'пр. Ленина 18', 180000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 19', 'Челябинск', 'пр. Ленина 19', 190000);
INSERT INTO project(name, city, address, budget) VALUES ('Проект 20', 'Челябинск', 'пр. Ленина 20', 200000);

INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (1,1,1,10);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (2,2,2,20);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (3,3,3,30);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (4,4,4,40);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (5,5,5,50);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (6,6,6,60);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (7,7,7,70);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (8,8,8,80);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (9,9,9,90);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (10,10,10,100);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (11,11,11,110);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (12,12,12,120);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (13,13,13,130);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (14,14,14,140);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (15,15,15,150);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (16,16,16,160);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (17,17,17,170);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (18,18,18,180);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (19,19,19,190);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (20,20,20,200);
INSERT INTO supply(id_detail, id_provider, id_project, number_of_details) VALUES (1,1,2,10);
